### ISSUE TITLE
v1 releases contain empty __init__.py

### ISSUE THREAD

**Issue by irnc** [blancadesal/mwsql#34]
Latest working release is v0.1.5. Newer releases from 1.0.0 up to latest 1.0.3 contain empty `__init__.py` which results in following error on `from mwsql import Dump`:

`ImportError: cannot import name 'Dump' from 'mwsql' (/usr/local/lib/python3.10/dist-packages/mwsql/__init__.py)`

**Comment by blancadesal** [comment]
Thank you for reporting this! Should be fixed now.
